export const SET_CLIENT_VENC='SET_CLIENT_VENC';
export const SET_CLIENT_DATA='SET_CLIENT_DATA';
export const SET_CLIENT_TYPE='SET_CLIENT_TYPE';
export const SET_CLIENT_VENCIMIENTOS='ADD_CLIENT_VENCIMIENTO'; 

export const ADD_CONTRIBUYENTE='ADD_CONTRIBUYENTE';
export const REMOVE_CONTRIBUYENTE='REMOVE_CONTRIBUYENTE'; 

export const LOAD_INDICADORES='LOAD_INDICADORES';
export const LOAD_NOTIFICACIONES='LOAD_NOTIFICACIONES';
export const LOAD_VENCIMIENTOS='LOAD_VENCIMIENTOS';



export const SET_AUTH_DATA='SET_AUTH_DATA';
export const REMOVE_AUTH_DATA='REMOVE_AUTH_DATA';
