export const SET_CLIENT_VENC='SET_CLIENT_VENC';
export const SET_CLIENT_DATA='SET_CLIENT_DATA';
export const SET_CLIENT_TYPE='SET_CLIENT_TYPE';
export const SET_EDIT_MODE='SET_EDIT_MODE';

export const SET_CLIENT_VENCIMIENTOS='ADD_CLIENT_VENCIMIENTO'; 

export const ADD_CLIENTE='ADD_CLIENTE';
export const UPDATE_CLIENTE='UPDATE_CLIENTE';
export const REMOVE_CLIENTE='REMOVE_CLIENTE'; 


export const LOAD_VENCIMIENTOS='LOAD_VENCIMIENTOS';



export const SET_SESSION_AUTH_DATA='SET_SESSION_AUTH_DATA';
export const SET_AUTH_DATA='SET_AUTH_DATA';
export const REMOVE_AUTH_DATA='REMOVE_AUTH_DATA';


export const SET_PROFILE_DATA='SET_PROFILE_DATA';

export const SET_INDICADORES_DATA='SET_INDICADORES_DATA';
export const SET_NOVEDADES_DATA='SET_NOVEDADES_DATA';


export const SELECT_CLIENTE='SELECT_CLIENTE';


